allow-nether=false
difficulty=peaceful
enable-command-block=true
force-gamemode=true
gamemode=creative
generate-structures=false
generator-settings={"biome":"minecraft:plains","features":false,"lakes":false,"layers":[]}
level-type=flat
max-players=1
online-mode=false
server-ip=127.0.0.1
spawn-monsters=false
