package dev.minecraftvideo.contracts;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.io.ByteArrayInputStream;
import java.util.Base64;
import org.junit.jupiter.api.Test;

final class VoxelWorldCompatibilityTest {
  // Generated by the Python encoder and intentionally decoded by Java.
  private static final String PYTHON_FIXTURE_BASE64 =
      "KLUv/SRZpQIApAQIARIEMjYuMhoTCAESD21pbmVjcmFmdDpzdG9uZRocCAISGHdoaXRlX2NvbmNyZXRlIgQIASABIgQQASACIgIiIAIqBggBEAEoIgIAtAg33OYTYjVZMg==";

  @Test
  void decodesPythonGoldenFixtureIdentically() throws Exception {
    var bytes = Base64.getDecoder().decode(PYTHON_FIXTURE_BASE64);
    var world = VoxelWorldReader.read(new ByteArrayInputStream(bytes));

    assertEquals(1, world.getSchemaVersion());
    assertEquals("26.2", world.getMinecraftVersion());
    assertEquals(2, world.getPaletteCount());
    assertEquals(4, world.getVoxelsCount());
    assertEquals(-1, world.getVoxels(0).getX());
    assertEquals(-1, world.getVoxels(1).getY());
    assertEquals(17, world.getVoxels(3).getY());
    assertEquals(-1, world.getBounds().getMinX());
    assertEquals(17, world.getBounds().getMaxY());
  }
}
