#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
IMAGE_TAG="${RECONSTRUCTION_IMAGE_TAG:-video-to-minecraft/reconstruction:colmap-4.0.4}"
CUDA_ARCHITECTURES="${RECONSTRUCTION_CUDA_ARCHITECTURES:-89}"
LOCK_FILE="${ROOT_DIR}/infra/containers/reconstruction-image.lock"
IID_FILE="$(mktemp)"
trap 'rm -f -- "${IID_FILE}"' EXIT

docker build \
  --file "${ROOT_DIR}/infra/containers/reconstruction.Dockerfile" \
  --build-arg "CUDA_ARCHITECTURES=${CUDA_ARCHITECTURES}" \
  --iidfile "${IID_FILE}" \
  --tag "${IMAGE_TAG}" \
  "${ROOT_DIR}"

IMAGE_ID="$(cat "${IID_FILE}")"
VERSION="$(docker run --rm "${IMAGE_ID}" colmap -h | sed -n '1p')"
CREATED="$(date --utc +%Y-%m-%dT%H:%M:%SZ)"

cat >"${LOCK_FILE}" <<EOF
# Generated by scripts/build_reconstruction_image.sh.
image_tag=${IMAGE_TAG}
image_id=${IMAGE_ID}
colmap_version=${VERSION}
colmap_commit=9c23f6942fe69962e06030905e77067c8673382f
cuda_architectures=${CUDA_ARCHITECTURES}
built_at=${CREATED}
EOF

printf 'Built %s\nImmutable local image ID: %s\nLock file: %s\n' "${IMAGE_TAG}" "${IMAGE_ID}" "${LOCK_FILE}"
