// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

@com.google.protobuf.Generated
public interface BoundsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraft_video.contracts.v1.Bounds)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 min_x = 1;</code>
   * @return The minX.
   */
  int getMinX();

  /**
   * <code>sint32 min_y = 2;</code>
   * @return The minY.
   */
  int getMinY();

  /**
   * <code>sint32 min_z = 3;</code>
   * @return The minZ.
   */
  int getMinZ();

  /**
   * <code>sint32 max_x = 4;</code>
   * @return The maxX.
   */
  int getMaxX();

  /**
   * <code>sint32 max_y = 5;</code>
   * @return The maxY.
   */
  int getMaxY();

  /**
   * <code>sint32 max_z = 6;</code>
   * @return The maxZ.
   */
  int getMaxZ();
}
