// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

/**
 * Protobuf type {@code minecraft_video.contracts.v1.Bounds}
 */
@com.google.protobuf.Generated
public final class Bounds extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minecraft_video.contracts.v1.Bounds)
    BoundsOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Bounds");
  }
  // Use Bounds.newBuilder() to construct.
  private Bounds(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Bounds() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Bounds_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Bounds_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Bounds_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.minecraftvideo.contracts.v1.Bounds.class, dev.minecraftvideo.contracts.v1.Bounds.Builder.class);
  }

  public static final int MIN_X_FIELD_NUMBER = 1;
  private int minX_ = 0;
  /**
   * <code>sint32 min_x = 1;</code>
   * @return The minX.
   */
  @java.lang.Override
  public int getMinX() {
    return minX_;
  }

  public static final int MIN_Y_FIELD_NUMBER = 2;
  private int minY_ = 0;
  /**
   * <code>sint32 min_y = 2;</code>
   * @return The minY.
   */
  @java.lang.Override
  public int getMinY() {
    return minY_;
  }

  public static final int MIN_Z_FIELD_NUMBER = 3;
  private int minZ_ = 0;
  /**
   * <code>sint32 min_z = 3;</code>
   * @return The minZ.
   */
  @java.lang.Override
  public int getMinZ() {
    return minZ_;
  }

  public static final int MAX_X_FIELD_NUMBER = 4;
  private int maxX_ = 0;
  /**
   * <code>sint32 max_x = 4;</code>
   * @return The maxX.
   */
  @java.lang.Override
  public int getMaxX() {
    return maxX_;
  }

  public static final int MAX_Y_FIELD_NUMBER = 5;
  private int maxY_ = 0;
  /**
   * <code>sint32 max_y = 5;</code>
   * @return The maxY.
   */
  @java.lang.Override
  public int getMaxY() {
    return maxY_;
  }

  public static final int MAX_Z_FIELD_NUMBER = 6;
  private int maxZ_ = 0;
  /**
   * <code>sint32 max_z = 6;</code>
   * @return The maxZ.
   */
  @java.lang.Override
  public int getMaxZ() {
    return maxZ_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (minX_ != 0) {
      output.writeSInt32(1, minX_);
    }
    if (minY_ != 0) {
      output.writeSInt32(2, minY_);
    }
    if (minZ_ != 0) {
      output.writeSInt32(3, minZ_);
    }
    if (maxX_ != 0) {
      output.writeSInt32(4, maxX_);
    }
    if (maxY_ != 0) {
      output.writeSInt32(5, maxY_);
    }
    if (maxZ_ != 0) {
      output.writeSInt32(6, maxZ_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (minX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, minX_);
    }
    if (minY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, minY_);
    }
    if (minZ_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, minZ_);
    }
    if (maxX_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(4, maxX_);
    }
    if (maxY_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(5, maxY_);
    }
    if (maxZ_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(6, maxZ_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.minecraftvideo.contracts.v1.Bounds)) {
      return super.equals(obj);
    }
    dev.minecraftvideo.contracts.v1.Bounds other = (dev.minecraftvideo.contracts.v1.Bounds) obj;

    if (getMinX()
        != other.getMinX()) return false;
    if (getMinY()
        != other.getMinY()) return false;
    if (getMinZ()
        != other.getMinZ()) return false;
    if (getMaxX()
        != other.getMaxX()) return false;
    if (getMaxY()
        != other.getMaxY()) return false;
    if (getMaxZ()
        != other.getMaxZ()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MIN_X_FIELD_NUMBER;
    hash = (53 * hash) + getMinX();
    hash = (37 * hash) + MIN_Y_FIELD_NUMBER;
    hash = (53 * hash) + getMinY();
    hash = (37 * hash) + MIN_Z_FIELD_NUMBER;
    hash = (53 * hash) + getMinZ();
    hash = (37 * hash) + MAX_X_FIELD_NUMBER;
    hash = (53 * hash) + getMaxX();
    hash = (37 * hash) + MAX_Y_FIELD_NUMBER;
    hash = (53 * hash) + getMaxY();
    hash = (37 * hash) + MAX_Z_FIELD_NUMBER;
    hash = (53 * hash) + getMaxZ();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.minecraftvideo.contracts.v1.Bounds parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.minecraftvideo.contracts.v1.Bounds parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.Bounds parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.minecraftvideo.contracts.v1.Bounds prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraft_video.contracts.v1.Bounds}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraft_video.contracts.v1.Bounds)
      dev.minecraftvideo.contracts.v1.BoundsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Bounds_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Bounds_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minecraftvideo.contracts.v1.Bounds.class, dev.minecraftvideo.contracts.v1.Bounds.Builder.class);
    }

    // Construct using dev.minecraftvideo.contracts.v1.Bounds.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      minX_ = 0;
      minY_ = 0;
      minZ_ = 0;
      maxX_ = 0;
      maxY_ = 0;
      maxZ_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Bounds_descriptor;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.Bounds getDefaultInstanceForType() {
      return dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance();
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.Bounds build() {
      dev.minecraftvideo.contracts.v1.Bounds result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.Bounds buildPartial() {
      dev.minecraftvideo.contracts.v1.Bounds result = new dev.minecraftvideo.contracts.v1.Bounds(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.minecraftvideo.contracts.v1.Bounds result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.minX_ = minX_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.minY_ = minY_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.minZ_ = minZ_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.maxX_ = maxX_;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.maxY_ = maxY_;
      }
      if (((from_bitField0_ & 0x00000020) != 0)) {
        result.maxZ_ = maxZ_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.minecraftvideo.contracts.v1.Bounds) {
        return mergeFrom((dev.minecraftvideo.contracts.v1.Bounds)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.minecraftvideo.contracts.v1.Bounds other) {
      if (other == dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance()) return this;
      if (other.getMinX() != 0) {
        setMinX(other.getMinX());
      }
      if (other.getMinY() != 0) {
        setMinY(other.getMinY());
      }
      if (other.getMinZ() != 0) {
        setMinZ(other.getMinZ());
      }
      if (other.getMaxX() != 0) {
        setMaxX(other.getMaxX());
      }
      if (other.getMaxY() != 0) {
        setMaxY(other.getMaxY());
      }
      if (other.getMaxZ() != 0) {
        setMaxZ(other.getMaxZ());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              minX_ = input.readSInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              minY_ = input.readSInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              minZ_ = input.readSInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              maxX_ = input.readSInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 40: {
              maxY_ = input.readSInt32();
              bitField0_ |= 0x00000010;
              break;
            } // case 40
            case 48: {
              maxZ_ = input.readSInt32();
              bitField0_ |= 0x00000020;
              break;
            } // case 48
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int minX_ ;
    /**
     * <code>sint32 min_x = 1;</code>
     * @return The minX.
     */
    @java.lang.Override
    public int getMinX() {
      return minX_;
    }
    /**
     * <code>sint32 min_x = 1;</code>
     * @param value The minX to set.
     * @return This builder for chaining.
     */
    public Builder setMinX(int value) {

      minX_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 min_x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      minX_ = 0;
      onChanged();
      return this;
    }

    private int minY_ ;
    /**
     * <code>sint32 min_y = 2;</code>
     * @return The minY.
     */
    @java.lang.Override
    public int getMinY() {
      return minY_;
    }
    /**
     * <code>sint32 min_y = 2;</code>
     * @param value The minY to set.
     * @return This builder for chaining.
     */
    public Builder setMinY(int value) {

      minY_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 min_y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      minY_ = 0;
      onChanged();
      return this;
    }

    private int minZ_ ;
    /**
     * <code>sint32 min_z = 3;</code>
     * @return The minZ.
     */
    @java.lang.Override
    public int getMinZ() {
      return minZ_;
    }
    /**
     * <code>sint32 min_z = 3;</code>
     * @param value The minZ to set.
     * @return This builder for chaining.
     */
    public Builder setMinZ(int value) {

      minZ_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 min_z = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      minZ_ = 0;
      onChanged();
      return this;
    }

    private int maxX_ ;
    /**
     * <code>sint32 max_x = 4;</code>
     * @return The maxX.
     */
    @java.lang.Override
    public int getMaxX() {
      return maxX_;
    }
    /**
     * <code>sint32 max_x = 4;</code>
     * @param value The maxX to set.
     * @return This builder for chaining.
     */
    public Builder setMaxX(int value) {

      maxX_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 max_x = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxX() {
      bitField0_ = (bitField0_ & ~0x00000008);
      maxX_ = 0;
      onChanged();
      return this;
    }

    private int maxY_ ;
    /**
     * <code>sint32 max_y = 5;</code>
     * @return The maxY.
     */
    @java.lang.Override
    public int getMaxY() {
      return maxY_;
    }
    /**
     * <code>sint32 max_y = 5;</code>
     * @param value The maxY to set.
     * @return This builder for chaining.
     */
    public Builder setMaxY(int value) {

      maxY_ = value;
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 max_y = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxY() {
      bitField0_ = (bitField0_ & ~0x00000010);
      maxY_ = 0;
      onChanged();
      return this;
    }

    private int maxZ_ ;
    /**
     * <code>sint32 max_z = 6;</code>
     * @return The maxZ.
     */
    @java.lang.Override
    public int getMaxZ() {
      return maxZ_;
    }
    /**
     * <code>sint32 max_z = 6;</code>
     * @param value The maxZ to set.
     * @return This builder for chaining.
     */
    public Builder setMaxZ(int value) {

      maxZ_ = value;
      bitField0_ |= 0x00000020;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 max_z = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearMaxZ() {
      bitField0_ = (bitField0_ & ~0x00000020);
      maxZ_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minecraft_video.contracts.v1.Bounds)
  }

  // @@protoc_insertion_point(class_scope:minecraft_video.contracts.v1.Bounds)
  private static final dev.minecraftvideo.contracts.v1.Bounds DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.minecraftvideo.contracts.v1.Bounds();
  }

  public static dev.minecraftvideo.contracts.v1.Bounds getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Bounds>
      PARSER = new com.google.protobuf.AbstractParser<Bounds>() {
    @java.lang.Override
    public Bounds parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Bounds> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Bounds> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.Bounds getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

