// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

@com.google.protobuf.Generated
public interface PaletteEntryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraft_video.contracts.v1.PaletteEntry)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string block_state = 2;</code>
   * @return The blockState.
   */
  java.lang.String getBlockState();
  /**
   * <code>string block_state = 2;</code>
   * @return The bytes for blockState.
   */
  com.google.protobuf.ByteString
      getBlockStateBytes();
}
