// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

/**
 * Protobuf type {@code minecraft_video.contracts.v1.PaletteEntry}
 */
@com.google.protobuf.Generated
public final class PaletteEntry extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minecraft_video.contracts.v1.PaletteEntry)
    PaletteEntryOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "PaletteEntry");
  }
  // Use PaletteEntry.newBuilder() to construct.
  private PaletteEntry(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private PaletteEntry() {
    blockState_ = "";
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_PaletteEntry_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.minecraftvideo.contracts.v1.PaletteEntry.class, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private int id_ = 0;
  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  @java.lang.Override
  public int getId() {
    return id_;
  }

  public static final int BLOCK_STATE_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object blockState_ = "";
  /**
   * <code>string block_state = 2;</code>
   * @return The blockState.
   */
  @java.lang.Override
  public java.lang.String getBlockState() {
    java.lang.Object ref = blockState_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      blockState_ = s;
      return s;
    }
  }
  /**
   * <code>string block_state = 2;</code>
   * @return The bytes for blockState.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getBlockStateBytes() {
    java.lang.Object ref = blockState_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      blockState_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0) {
      output.writeUInt32(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blockState_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, blockState_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, id_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(blockState_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, blockState_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.minecraftvideo.contracts.v1.PaletteEntry)) {
      return super.equals(obj);
    }
    dev.minecraftvideo.contracts.v1.PaletteEntry other = (dev.minecraftvideo.contracts.v1.PaletteEntry) obj;

    if (getId()
        != other.getId()) return false;
    if (!getBlockState()
        .equals(other.getBlockState())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + BLOCK_STATE_FIELD_NUMBER;
    hash = (53 * hash) + getBlockState().hashCode();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.PaletteEntry parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.minecraftvideo.contracts.v1.PaletteEntry prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraft_video.contracts.v1.PaletteEntry}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraft_video.contracts.v1.PaletteEntry)
      dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_PaletteEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minecraftvideo.contracts.v1.PaletteEntry.class, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder.class);
    }

    // Construct using dev.minecraftvideo.contracts.v1.PaletteEntry.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = 0;
      blockState_ = "";
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.PaletteEntry getDefaultInstanceForType() {
      return dev.minecraftvideo.contracts.v1.PaletteEntry.getDefaultInstance();
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.PaletteEntry build() {
      dev.minecraftvideo.contracts.v1.PaletteEntry result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.PaletteEntry buildPartial() {
      dev.minecraftvideo.contracts.v1.PaletteEntry result = new dev.minecraftvideo.contracts.v1.PaletteEntry(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.minecraftvideo.contracts.v1.PaletteEntry result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.blockState_ = blockState_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.minecraftvideo.contracts.v1.PaletteEntry) {
        return mergeFrom((dev.minecraftvideo.contracts.v1.PaletteEntry)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.minecraftvideo.contracts.v1.PaletteEntry other) {
      if (other == dev.minecraftvideo.contracts.v1.PaletteEntry.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getBlockState().isEmpty()) {
        blockState_ = other.blockState_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              id_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              blockState_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>uint32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(int value) {

      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 id = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      bitField0_ = (bitField0_ & ~0x00000001);
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object blockState_ = "";
    /**
     * <code>string block_state = 2;</code>
     * @return The blockState.
     */
    public java.lang.String getBlockState() {
      java.lang.Object ref = blockState_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        blockState_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string block_state = 2;</code>
     * @return The bytes for blockState.
     */
    public com.google.protobuf.ByteString
        getBlockStateBytes() {
      java.lang.Object ref = blockState_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        blockState_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string block_state = 2;</code>
     * @param value The blockState to set.
     * @return This builder for chaining.
     */
    public Builder setBlockState(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      blockState_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string block_state = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearBlockState() {
      blockState_ = getDefaultInstance().getBlockState();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string block_state = 2;</code>
     * @param value The bytes for blockState to set.
     * @return This builder for chaining.
     */
    public Builder setBlockStateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      blockState_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minecraft_video.contracts.v1.PaletteEntry)
  }

  // @@protoc_insertion_point(class_scope:minecraft_video.contracts.v1.PaletteEntry)
  private static final dev.minecraftvideo.contracts.v1.PaletteEntry DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.minecraftvideo.contracts.v1.PaletteEntry();
  }

  public static dev.minecraftvideo.contracts.v1.PaletteEntry getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PaletteEntry>
      PARSER = new com.google.protobuf.AbstractParser<PaletteEntry>() {
    @java.lang.Override
    public PaletteEntry parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<PaletteEntry> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PaletteEntry> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.PaletteEntry getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

