// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

@com.google.protobuf.Generated
public final class VoxelWorldProto extends com.google.protobuf.GeneratedFile {
  private VoxelWorldProto() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "VoxelWorldProto");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minecraft_video_contracts_v1_VoxelWorld_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minecraft_video_contracts_v1_PaletteEntry_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraft_video_contracts_v1_Voxel_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minecraft_video_contracts_v1_Voxel_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_minecraft_video_contracts_v1_Bounds_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_minecraft_video_contracts_v1_Bounds_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021voxel_world.proto\022\034minecraft_video.con" +
      "tracts.v1\"\347\001\n\nVoxelWorld\022\026\n\016schema_versi" +
      "on\030\001 \001(\r\022\031\n\021minecraft_version\030\002 \001(\t\022;\n\007p" +
      "alette\030\003 \003(\0132*.minecraft_video.contracts" +
      ".v1.PaletteEntry\0223\n\006voxels\030\004 \003(\0132#.minec" +
      "raft_video.contracts.v1.Voxel\0224\n\006bounds\030" +
      "\005 \001(\0132$.minecraft_video.contracts.v1.Bou" +
      "nds\"/\n\014PaletteEntry\022\n\n\002id\030\001 \001(\r\022\023\n\013block" +
      "_state\030\002 \001(\t\"<\n\005Voxel\022\t\n\001x\030\001 \001(\021\022\t\n\001y\030\002 " +
      "\001(\021\022\t\n\001z\030\003 \001(\021\022\022\n\npalette_id\030\004 \001(\r\"b\n\006Bo" +
      "unds\022\r\n\005min_x\030\001 \001(\021\022\r\n\005min_y\030\002 \001(\021\022\r\n\005mi" +
      "n_z\030\003 \001(\021\022\r\n\005max_x\030\004 \001(\021\022\r\n\005max_y\030\005 \001(\021\022" +
      "\r\n\005max_z\030\006 \001(\021B4\n\037dev.minecraftvideo.con" +
      "tracts.v1B\017VoxelWorldProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_minecraft_video_contracts_v1_VoxelWorld_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor,
        new java.lang.String[] { "SchemaVersion", "MinecraftVersion", "Palette", "Voxels", "Bounds", });
    internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_minecraft_video_contracts_v1_PaletteEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minecraft_video_contracts_v1_PaletteEntry_descriptor,
        new java.lang.String[] { "Id", "BlockState", });
    internal_static_minecraft_video_contracts_v1_Voxel_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_minecraft_video_contracts_v1_Voxel_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minecraft_video_contracts_v1_Voxel_descriptor,
        new java.lang.String[] { "X", "Y", "Z", "PaletteId", });
    internal_static_minecraft_video_contracts_v1_Bounds_descriptor =
      getDescriptor().getMessageType(3);
    internal_static_minecraft_video_contracts_v1_Bounds_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_minecraft_video_contracts_v1_Bounds_descriptor,
        new java.lang.String[] { "MinX", "MinY", "MinZ", "MaxX", "MaxY", "MaxZ", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
