// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

/**
 * <pre>
 * Stable, language-neutral handoff from reconstruction to world generation.
 * </pre>
 *
 * Protobuf type {@code minecraft_video.contracts.v1.VoxelWorld}
 */
@com.google.protobuf.Generated
public final class VoxelWorld extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minecraft_video.contracts.v1.VoxelWorld)
    VoxelWorldOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "VoxelWorld");
  }
  // Use VoxelWorld.newBuilder() to construct.
  private VoxelWorld(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private VoxelWorld() {
    minecraftVersion_ = "";
    palette_ = java.util.Collections.emptyList();
    voxels_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_VoxelWorld_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.minecraftvideo.contracts.v1.VoxelWorld.class, dev.minecraftvideo.contracts.v1.VoxelWorld.Builder.class);
  }

  private int bitField0_;
  public static final int SCHEMA_VERSION_FIELD_NUMBER = 1;
  private int schemaVersion_ = 0;
  /**
   * <code>uint32 schema_version = 1;</code>
   * @return The schemaVersion.
   */
  @java.lang.Override
  public int getSchemaVersion() {
    return schemaVersion_;
  }

  public static final int MINECRAFT_VERSION_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object minecraftVersion_ = "";
  /**
   * <code>string minecraft_version = 2;</code>
   * @return The minecraftVersion.
   */
  @java.lang.Override
  public java.lang.String getMinecraftVersion() {
    java.lang.Object ref = minecraftVersion_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      minecraftVersion_ = s;
      return s;
    }
  }
  /**
   * <code>string minecraft_version = 2;</code>
   * @return The bytes for minecraftVersion.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getMinecraftVersionBytes() {
    java.lang.Object ref = minecraftVersion_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      minecraftVersion_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int PALETTE_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private java.util.List<dev.minecraftvideo.contracts.v1.PaletteEntry> palette_;
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  @java.lang.Override
  public java.util.List<dev.minecraftvideo.contracts.v1.PaletteEntry> getPaletteList() {
    return palette_;
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder> 
      getPaletteOrBuilderList() {
    return palette_;
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  @java.lang.Override
  public int getPaletteCount() {
    return palette_.size();
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.PaletteEntry getPalette(int index) {
    return palette_.get(index);
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder getPaletteOrBuilder(
      int index) {
    return palette_.get(index);
  }

  public static final int VOXELS_FIELD_NUMBER = 4;
  @SuppressWarnings("serial")
  private java.util.List<dev.minecraftvideo.contracts.v1.Voxel> voxels_;
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  @java.lang.Override
  public java.util.List<dev.minecraftvideo.contracts.v1.Voxel> getVoxelsList() {
    return voxels_;
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  @java.lang.Override
  public java.util.List<? extends dev.minecraftvideo.contracts.v1.VoxelOrBuilder> 
      getVoxelsOrBuilderList() {
    return voxels_;
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  @java.lang.Override
  public int getVoxelsCount() {
    return voxels_.size();
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.Voxel getVoxels(int index) {
    return voxels_.get(index);
  }
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.VoxelOrBuilder getVoxelsOrBuilder(
      int index) {
    return voxels_.get(index);
  }

  public static final int BOUNDS_FIELD_NUMBER = 5;
  private dev.minecraftvideo.contracts.v1.Bounds bounds_;
  /**
   * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
   * @return Whether the bounds field is set.
   */
  @java.lang.Override
  public boolean hasBounds() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
   * @return The bounds.
   */
  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.Bounds getBounds() {
    return bounds_ == null ? dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance() : bounds_;
  }
  /**
   * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
   */
  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.BoundsOrBuilder getBoundsOrBuilder() {
    return bounds_ == null ? dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance() : bounds_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (schemaVersion_ != 0) {
      output.writeUInt32(1, schemaVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(minecraftVersion_)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, minecraftVersion_);
    }
    for (int i = 0; i < palette_.size(); i++) {
      output.writeMessage(3, palette_.get(i));
    }
    for (int i = 0; i < voxels_.size(); i++) {
      output.writeMessage(4, voxels_.get(i));
    }
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(5, getBounds());
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (schemaVersion_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, schemaVersion_);
    }
    if (!com.google.protobuf.GeneratedMessage.isStringEmpty(minecraftVersion_)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, minecraftVersion_);
    }

        {
          final int count = palette_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(palette_.get(i));
          }
          size += 1 * count;
        }

        {
          final int count = voxels_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(voxels_.get(i));
          }
          size += 1 * count;
        }
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getBounds());
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.minecraftvideo.contracts.v1.VoxelWorld)) {
      return super.equals(obj);
    }
    dev.minecraftvideo.contracts.v1.VoxelWorld other = (dev.minecraftvideo.contracts.v1.VoxelWorld) obj;

    if (getSchemaVersion()
        != other.getSchemaVersion()) return false;
    if (!getMinecraftVersion()
        .equals(other.getMinecraftVersion())) return false;
    if (!getPaletteList()
        .equals(other.getPaletteList())) return false;
    if (!getVoxelsList()
        .equals(other.getVoxelsList())) return false;
    if (hasBounds() != other.hasBounds()) return false;
    if (hasBounds()) {
      if (!getBounds()
          .equals(other.getBounds())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + SCHEMA_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getSchemaVersion();
    hash = (37 * hash) + MINECRAFT_VERSION_FIELD_NUMBER;
    hash = (53 * hash) + getMinecraftVersion().hashCode();
    if (getPaletteCount() > 0) {
      hash = (37 * hash) + PALETTE_FIELD_NUMBER;
      hash = (53 * hash) + getPaletteList().hashCode();
    }
    if (getVoxelsCount() > 0) {
      hash = (37 * hash) + VOXELS_FIELD_NUMBER;
      hash = (53 * hash) + getVoxelsList().hashCode();
    }
    if (hasBounds()) {
      hash = (37 * hash) + BOUNDS_FIELD_NUMBER;
      hash = (53 * hash) + getBounds().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.VoxelWorld parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.minecraftvideo.contracts.v1.VoxelWorld prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * Stable, language-neutral handoff from reconstruction to world generation.
   * </pre>
   *
   * Protobuf type {@code minecraft_video.contracts.v1.VoxelWorld}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraft_video.contracts.v1.VoxelWorld)
      dev.minecraftvideo.contracts.v1.VoxelWorldOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_VoxelWorld_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minecraftvideo.contracts.v1.VoxelWorld.class, dev.minecraftvideo.contracts.v1.VoxelWorld.Builder.class);
    }

    // Construct using dev.minecraftvideo.contracts.v1.VoxelWorld.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetPaletteFieldBuilder();
        internalGetVoxelsFieldBuilder();
        internalGetBoundsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      schemaVersion_ = 0;
      minecraftVersion_ = "";
      if (paletteBuilder_ == null) {
        palette_ = java.util.Collections.emptyList();
      } else {
        palette_ = null;
        paletteBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000004);
      if (voxelsBuilder_ == null) {
        voxels_ = java.util.Collections.emptyList();
      } else {
        voxels_ = null;
        voxelsBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000008);
      bounds_ = null;
      if (boundsBuilder_ != null) {
        boundsBuilder_.dispose();
        boundsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_VoxelWorld_descriptor;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.VoxelWorld getDefaultInstanceForType() {
      return dev.minecraftvideo.contracts.v1.VoxelWorld.getDefaultInstance();
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.VoxelWorld build() {
      dev.minecraftvideo.contracts.v1.VoxelWorld result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.VoxelWorld buildPartial() {
      dev.minecraftvideo.contracts.v1.VoxelWorld result = new dev.minecraftvideo.contracts.v1.VoxelWorld(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(dev.minecraftvideo.contracts.v1.VoxelWorld result) {
      if (paletteBuilder_ == null) {
        if (((bitField0_ & 0x00000004) != 0)) {
          palette_ = java.util.Collections.unmodifiableList(palette_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.palette_ = palette_;
      } else {
        result.palette_ = paletteBuilder_.build();
      }
      if (voxelsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) != 0)) {
          voxels_ = java.util.Collections.unmodifiableList(voxels_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.voxels_ = voxels_;
      } else {
        result.voxels_ = voxelsBuilder_.build();
      }
    }

    private void buildPartial0(dev.minecraftvideo.contracts.v1.VoxelWorld result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.schemaVersion_ = schemaVersion_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.minecraftVersion_ = minecraftVersion_;
      }
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.bounds_ = boundsBuilder_ == null
            ? bounds_
            : boundsBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.minecraftvideo.contracts.v1.VoxelWorld) {
        return mergeFrom((dev.minecraftvideo.contracts.v1.VoxelWorld)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.minecraftvideo.contracts.v1.VoxelWorld other) {
      if (other == dev.minecraftvideo.contracts.v1.VoxelWorld.getDefaultInstance()) return this;
      if (other.getSchemaVersion() != 0) {
        setSchemaVersion(other.getSchemaVersion());
      }
      if (!other.getMinecraftVersion().isEmpty()) {
        minecraftVersion_ = other.minecraftVersion_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (paletteBuilder_ == null) {
        if (!other.palette_.isEmpty()) {
          if (palette_.isEmpty()) {
            palette_ = other.palette_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePaletteIsMutable();
            palette_.addAll(other.palette_);
          }
          onChanged();
        }
      } else {
        if (!other.palette_.isEmpty()) {
          if (paletteBuilder_.isEmpty()) {
            paletteBuilder_.dispose();
            paletteBuilder_ = null;
            palette_ = other.palette_;
            bitField0_ = (bitField0_ & ~0x00000004);
            paletteBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetPaletteFieldBuilder() : null;
          } else {
            paletteBuilder_.addAllMessages(other.palette_);
          }
        }
      }
      if (voxelsBuilder_ == null) {
        if (!other.voxels_.isEmpty()) {
          if (voxels_.isEmpty()) {
            voxels_ = other.voxels_;
            bitField0_ = (bitField0_ & ~0x00000008);
          } else {
            ensureVoxelsIsMutable();
            voxels_.addAll(other.voxels_);
          }
          onChanged();
        }
      } else {
        if (!other.voxels_.isEmpty()) {
          if (voxelsBuilder_.isEmpty()) {
            voxelsBuilder_.dispose();
            voxelsBuilder_ = null;
            voxels_ = other.voxels_;
            bitField0_ = (bitField0_ & ~0x00000008);
            voxelsBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetVoxelsFieldBuilder() : null;
          } else {
            voxelsBuilder_.addAllMessages(other.voxels_);
          }
        }
      }
      if (other.hasBounds()) {
        mergeBounds(other.getBounds());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              schemaVersion_ = input.readUInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 18: {
              minecraftVersion_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              dev.minecraftvideo.contracts.v1.PaletteEntry m =
                  input.readMessage(
                      dev.minecraftvideo.contracts.v1.PaletteEntry.parser(),
                      extensionRegistry);
              if (paletteBuilder_ == null) {
                ensurePaletteIsMutable();
                palette_.add(m);
              } else {
                paletteBuilder_.addMessage(m);
              }
              break;
            } // case 26
            case 34: {
              dev.minecraftvideo.contracts.v1.Voxel m =
                  input.readMessage(
                      dev.minecraftvideo.contracts.v1.Voxel.parser(),
                      extensionRegistry);
              if (voxelsBuilder_ == null) {
                ensureVoxelsIsMutable();
                voxels_.add(m);
              } else {
                voxelsBuilder_.addMessage(m);
              }
              break;
            } // case 34
            case 42: {
              input.readMessage(
                  internalGetBoundsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int schemaVersion_ ;
    /**
     * <code>uint32 schema_version = 1;</code>
     * @return The schemaVersion.
     */
    @java.lang.Override
    public int getSchemaVersion() {
      return schemaVersion_;
    }
    /**
     * <code>uint32 schema_version = 1;</code>
     * @param value The schemaVersion to set.
     * @return This builder for chaining.
     */
    public Builder setSchemaVersion(int value) {

      schemaVersion_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 schema_version = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearSchemaVersion() {
      bitField0_ = (bitField0_ & ~0x00000001);
      schemaVersion_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object minecraftVersion_ = "";
    /**
     * <code>string minecraft_version = 2;</code>
     * @return The minecraftVersion.
     */
    public java.lang.String getMinecraftVersion() {
      java.lang.Object ref = minecraftVersion_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        minecraftVersion_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string minecraft_version = 2;</code>
     * @return The bytes for minecraftVersion.
     */
    public com.google.protobuf.ByteString
        getMinecraftVersionBytes() {
      java.lang.Object ref = minecraftVersion_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        minecraftVersion_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string minecraft_version = 2;</code>
     * @param value The minecraftVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMinecraftVersion(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      minecraftVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string minecraft_version = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearMinecraftVersion() {
      minecraftVersion_ = getDefaultInstance().getMinecraftVersion();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string minecraft_version = 2;</code>
     * @param value The bytes for minecraftVersion to set.
     * @return This builder for chaining.
     */
    public Builder setMinecraftVersionBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      minecraftVersion_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.util.List<dev.minecraftvideo.contracts.v1.PaletteEntry> palette_ =
      java.util.Collections.emptyList();
    private void ensurePaletteIsMutable() {
      if (!((bitField0_ & 0x00000004) != 0)) {
        palette_ = new java.util.ArrayList<dev.minecraftvideo.contracts.v1.PaletteEntry>(palette_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        dev.minecraftvideo.contracts.v1.PaletteEntry, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder, dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder> paletteBuilder_;

    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public java.util.List<dev.minecraftvideo.contracts.v1.PaletteEntry> getPaletteList() {
      if (paletteBuilder_ == null) {
        return java.util.Collections.unmodifiableList(palette_);
      } else {
        return paletteBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public int getPaletteCount() {
      if (paletteBuilder_ == null) {
        return palette_.size();
      } else {
        return paletteBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public dev.minecraftvideo.contracts.v1.PaletteEntry getPalette(int index) {
      if (paletteBuilder_ == null) {
        return palette_.get(index);
      } else {
        return paletteBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder setPalette(
        int index, dev.minecraftvideo.contracts.v1.PaletteEntry value) {
      if (paletteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaletteIsMutable();
        palette_.set(index, value);
        onChanged();
      } else {
        paletteBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder setPalette(
        int index, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder builderForValue) {
      if (paletteBuilder_ == null) {
        ensurePaletteIsMutable();
        palette_.set(index, builderForValue.build());
        onChanged();
      } else {
        paletteBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder addPalette(dev.minecraftvideo.contracts.v1.PaletteEntry value) {
      if (paletteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaletteIsMutable();
        palette_.add(value);
        onChanged();
      } else {
        paletteBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder addPalette(
        int index, dev.minecraftvideo.contracts.v1.PaletteEntry value) {
      if (paletteBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePaletteIsMutable();
        palette_.add(index, value);
        onChanged();
      } else {
        paletteBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder addPalette(
        dev.minecraftvideo.contracts.v1.PaletteEntry.Builder builderForValue) {
      if (paletteBuilder_ == null) {
        ensurePaletteIsMutable();
        palette_.add(builderForValue.build());
        onChanged();
      } else {
        paletteBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder addPalette(
        int index, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder builderForValue) {
      if (paletteBuilder_ == null) {
        ensurePaletteIsMutable();
        palette_.add(index, builderForValue.build());
        onChanged();
      } else {
        paletteBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder addAllPalette(
        java.lang.Iterable<? extends dev.minecraftvideo.contracts.v1.PaletteEntry> values) {
      if (paletteBuilder_ == null) {
        ensurePaletteIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, palette_);
        onChanged();
      } else {
        paletteBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder clearPalette() {
      if (paletteBuilder_ == null) {
        palette_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        paletteBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public Builder removePalette(int index) {
      if (paletteBuilder_ == null) {
        ensurePaletteIsMutable();
        palette_.remove(index);
        onChanged();
      } else {
        paletteBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public dev.minecraftvideo.contracts.v1.PaletteEntry.Builder getPaletteBuilder(
        int index) {
      return internalGetPaletteFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder getPaletteOrBuilder(
        int index) {
      if (paletteBuilder_ == null) {
        return palette_.get(index);  } else {
        return paletteBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public java.util.List<? extends dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder> 
         getPaletteOrBuilderList() {
      if (paletteBuilder_ != null) {
        return paletteBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(palette_);
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public dev.minecraftvideo.contracts.v1.PaletteEntry.Builder addPaletteBuilder() {
      return internalGetPaletteFieldBuilder().addBuilder(
          dev.minecraftvideo.contracts.v1.PaletteEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public dev.minecraftvideo.contracts.v1.PaletteEntry.Builder addPaletteBuilder(
        int index) {
      return internalGetPaletteFieldBuilder().addBuilder(
          index, dev.minecraftvideo.contracts.v1.PaletteEntry.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
     */
    public java.util.List<dev.minecraftvideo.contracts.v1.PaletteEntry.Builder> 
         getPaletteBuilderList() {
      return internalGetPaletteFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        dev.minecraftvideo.contracts.v1.PaletteEntry, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder, dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder> 
        internalGetPaletteFieldBuilder() {
      if (paletteBuilder_ == null) {
        paletteBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            dev.minecraftvideo.contracts.v1.PaletteEntry, dev.minecraftvideo.contracts.v1.PaletteEntry.Builder, dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder>(
                palette_,
                ((bitField0_ & 0x00000004) != 0),
                getParentForChildren(),
                isClean());
        palette_ = null;
      }
      return paletteBuilder_;
    }

    private java.util.List<dev.minecraftvideo.contracts.v1.Voxel> voxels_ =
      java.util.Collections.emptyList();
    private void ensureVoxelsIsMutable() {
      if (!((bitField0_ & 0x00000008) != 0)) {
        voxels_ = new java.util.ArrayList<dev.minecraftvideo.contracts.v1.Voxel>(voxels_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        dev.minecraftvideo.contracts.v1.Voxel, dev.minecraftvideo.contracts.v1.Voxel.Builder, dev.minecraftvideo.contracts.v1.VoxelOrBuilder> voxelsBuilder_;

    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public java.util.List<dev.minecraftvideo.contracts.v1.Voxel> getVoxelsList() {
      if (voxelsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(voxels_);
      } else {
        return voxelsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public int getVoxelsCount() {
      if (voxelsBuilder_ == null) {
        return voxels_.size();
      } else {
        return voxelsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public dev.minecraftvideo.contracts.v1.Voxel getVoxels(int index) {
      if (voxelsBuilder_ == null) {
        return voxels_.get(index);
      } else {
        return voxelsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder setVoxels(
        int index, dev.minecraftvideo.contracts.v1.Voxel value) {
      if (voxelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVoxelsIsMutable();
        voxels_.set(index, value);
        onChanged();
      } else {
        voxelsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder setVoxels(
        int index, dev.minecraftvideo.contracts.v1.Voxel.Builder builderForValue) {
      if (voxelsBuilder_ == null) {
        ensureVoxelsIsMutable();
        voxels_.set(index, builderForValue.build());
        onChanged();
      } else {
        voxelsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder addVoxels(dev.minecraftvideo.contracts.v1.Voxel value) {
      if (voxelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVoxelsIsMutable();
        voxels_.add(value);
        onChanged();
      } else {
        voxelsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder addVoxels(
        int index, dev.minecraftvideo.contracts.v1.Voxel value) {
      if (voxelsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureVoxelsIsMutable();
        voxels_.add(index, value);
        onChanged();
      } else {
        voxelsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder addVoxels(
        dev.minecraftvideo.contracts.v1.Voxel.Builder builderForValue) {
      if (voxelsBuilder_ == null) {
        ensureVoxelsIsMutable();
        voxels_.add(builderForValue.build());
        onChanged();
      } else {
        voxelsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder addVoxels(
        int index, dev.minecraftvideo.contracts.v1.Voxel.Builder builderForValue) {
      if (voxelsBuilder_ == null) {
        ensureVoxelsIsMutable();
        voxels_.add(index, builderForValue.build());
        onChanged();
      } else {
        voxelsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder addAllVoxels(
        java.lang.Iterable<? extends dev.minecraftvideo.contracts.v1.Voxel> values) {
      if (voxelsBuilder_ == null) {
        ensureVoxelsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, voxels_);
        onChanged();
      } else {
        voxelsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder clearVoxels() {
      if (voxelsBuilder_ == null) {
        voxels_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        voxelsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public Builder removeVoxels(int index) {
      if (voxelsBuilder_ == null) {
        ensureVoxelsIsMutable();
        voxels_.remove(index);
        onChanged();
      } else {
        voxelsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public dev.minecraftvideo.contracts.v1.Voxel.Builder getVoxelsBuilder(
        int index) {
      return internalGetVoxelsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public dev.minecraftvideo.contracts.v1.VoxelOrBuilder getVoxelsOrBuilder(
        int index) {
      if (voxelsBuilder_ == null) {
        return voxels_.get(index);  } else {
        return voxelsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public java.util.List<? extends dev.minecraftvideo.contracts.v1.VoxelOrBuilder> 
         getVoxelsOrBuilderList() {
      if (voxelsBuilder_ != null) {
        return voxelsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(voxels_);
      }
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public dev.minecraftvideo.contracts.v1.Voxel.Builder addVoxelsBuilder() {
      return internalGetVoxelsFieldBuilder().addBuilder(
          dev.minecraftvideo.contracts.v1.Voxel.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public dev.minecraftvideo.contracts.v1.Voxel.Builder addVoxelsBuilder(
        int index) {
      return internalGetVoxelsFieldBuilder().addBuilder(
          index, dev.minecraftvideo.contracts.v1.Voxel.getDefaultInstance());
    }
    /**
     * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
     */
    public java.util.List<dev.minecraftvideo.contracts.v1.Voxel.Builder> 
         getVoxelsBuilderList() {
      return internalGetVoxelsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        dev.minecraftvideo.contracts.v1.Voxel, dev.minecraftvideo.contracts.v1.Voxel.Builder, dev.minecraftvideo.contracts.v1.VoxelOrBuilder> 
        internalGetVoxelsFieldBuilder() {
      if (voxelsBuilder_ == null) {
        voxelsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            dev.minecraftvideo.contracts.v1.Voxel, dev.minecraftvideo.contracts.v1.Voxel.Builder, dev.minecraftvideo.contracts.v1.VoxelOrBuilder>(
                voxels_,
                ((bitField0_ & 0x00000008) != 0),
                getParentForChildren(),
                isClean());
        voxels_ = null;
      }
      return voxelsBuilder_;
    }

    private dev.minecraftvideo.contracts.v1.Bounds bounds_;
    private com.google.protobuf.SingleFieldBuilder<
        dev.minecraftvideo.contracts.v1.Bounds, dev.minecraftvideo.contracts.v1.Bounds.Builder, dev.minecraftvideo.contracts.v1.BoundsOrBuilder> boundsBuilder_;
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     * @return Whether the bounds field is set.
     */
    public boolean hasBounds() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     * @return The bounds.
     */
    public dev.minecraftvideo.contracts.v1.Bounds getBounds() {
      if (boundsBuilder_ == null) {
        return bounds_ == null ? dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance() : bounds_;
      } else {
        return boundsBuilder_.getMessage();
      }
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    public Builder setBounds(dev.minecraftvideo.contracts.v1.Bounds value) {
      if (boundsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        bounds_ = value;
      } else {
        boundsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    public Builder setBounds(
        dev.minecraftvideo.contracts.v1.Bounds.Builder builderForValue) {
      if (boundsBuilder_ == null) {
        bounds_ = builderForValue.build();
      } else {
        boundsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    public Builder mergeBounds(dev.minecraftvideo.contracts.v1.Bounds value) {
      if (boundsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          bounds_ != null &&
          bounds_ != dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance()) {
          getBoundsBuilder().mergeFrom(value);
        } else {
          bounds_ = value;
        }
      } else {
        boundsBuilder_.mergeFrom(value);
      }
      if (bounds_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    public Builder clearBounds() {
      bitField0_ = (bitField0_ & ~0x00000010);
      bounds_ = null;
      if (boundsBuilder_ != null) {
        boundsBuilder_.dispose();
        boundsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    public dev.minecraftvideo.contracts.v1.Bounds.Builder getBoundsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetBoundsFieldBuilder().getBuilder();
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    public dev.minecraftvideo.contracts.v1.BoundsOrBuilder getBoundsOrBuilder() {
      if (boundsBuilder_ != null) {
        return boundsBuilder_.getMessageOrBuilder();
      } else {
        return bounds_ == null ?
            dev.minecraftvideo.contracts.v1.Bounds.getDefaultInstance() : bounds_;
      }
    }
    /**
     * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        dev.minecraftvideo.contracts.v1.Bounds, dev.minecraftvideo.contracts.v1.Bounds.Builder, dev.minecraftvideo.contracts.v1.BoundsOrBuilder> 
        internalGetBoundsFieldBuilder() {
      if (boundsBuilder_ == null) {
        boundsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            dev.minecraftvideo.contracts.v1.Bounds, dev.minecraftvideo.contracts.v1.Bounds.Builder, dev.minecraftvideo.contracts.v1.BoundsOrBuilder>(
                getBounds(),
                getParentForChildren(),
                isClean());
        bounds_ = null;
      }
      return boundsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:minecraft_video.contracts.v1.VoxelWorld)
  }

  // @@protoc_insertion_point(class_scope:minecraft_video.contracts.v1.VoxelWorld)
  private static final dev.minecraftvideo.contracts.v1.VoxelWorld DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.minecraftvideo.contracts.v1.VoxelWorld();
  }

  public static dev.minecraftvideo.contracts.v1.VoxelWorld getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoxelWorld>
      PARSER = new com.google.protobuf.AbstractParser<VoxelWorld>() {
    @java.lang.Override
    public VoxelWorld parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<VoxelWorld> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoxelWorld> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.VoxelWorld getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

