// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

@com.google.protobuf.Generated
public interface VoxelOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraft_video.contracts.v1.Voxel)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>sint32 x = 1;</code>
   * @return The x.
   */
  int getX();

  /**
   * <code>sint32 y = 2;</code>
   * @return The y.
   */
  int getY();

  /**
   * <code>sint32 z = 3;</code>
   * @return The z.
   */
  int getZ();

  /**
   * <code>uint32 palette_id = 4;</code>
   * @return The paletteId.
   */
  int getPaletteId();
}
