// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

/**
 * Protobuf type {@code minecraft_video.contracts.v1.Voxel}
 */
@com.google.protobuf.Generated
public final class Voxel extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:minecraft_video.contracts.v1.Voxel)
    VoxelOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 35,
      /* patch= */ 1,
      /* suffix= */ "",
      "Voxel");
  }
  // Use Voxel.newBuilder() to construct.
  private Voxel(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Voxel() {
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Voxel_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Voxel_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Voxel_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            dev.minecraftvideo.contracts.v1.Voxel.class, dev.minecraftvideo.contracts.v1.Voxel.Builder.class);
  }

  public static final int X_FIELD_NUMBER = 1;
  private int x_ = 0;
  /**
   * <code>sint32 x = 1;</code>
   * @return The x.
   */
  @java.lang.Override
  public int getX() {
    return x_;
  }

  public static final int Y_FIELD_NUMBER = 2;
  private int y_ = 0;
  /**
   * <code>sint32 y = 2;</code>
   * @return The y.
   */
  @java.lang.Override
  public int getY() {
    return y_;
  }

  public static final int Z_FIELD_NUMBER = 3;
  private int z_ = 0;
  /**
   * <code>sint32 z = 3;</code>
   * @return The z.
   */
  @java.lang.Override
  public int getZ() {
    return z_;
  }

  public static final int PALETTE_ID_FIELD_NUMBER = 4;
  private int paletteId_ = 0;
  /**
   * <code>uint32 palette_id = 4;</code>
   * @return The paletteId.
   */
  @java.lang.Override
  public int getPaletteId() {
    return paletteId_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (x_ != 0) {
      output.writeSInt32(1, x_);
    }
    if (y_ != 0) {
      output.writeSInt32(2, y_);
    }
    if (z_ != 0) {
      output.writeSInt32(3, z_);
    }
    if (paletteId_ != 0) {
      output.writeUInt32(4, paletteId_);
    }
    getUnknownFields().writeTo(output);
  }
  private int computeSerializedSize_0() {
    int size = 0;
    if (x_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(1, x_);
    }
    if (y_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(2, y_);
    }
    if (z_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeSInt32Size(3, z_);
    }
    if (paletteId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(4, paletteId_);
    }
    return size;
  }
  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    size += computeSerializedSize_0();
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof dev.minecraftvideo.contracts.v1.Voxel)) {
      return super.equals(obj);
    }
    dev.minecraftvideo.contracts.v1.Voxel other = (dev.minecraftvideo.contracts.v1.Voxel) obj;

    if (getX()
        != other.getX()) return false;
    if (getY()
        != other.getY()) return false;
    if (getZ()
        != other.getZ()) return false;
    if (getPaletteId()
        != other.getPaletteId()) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + X_FIELD_NUMBER;
    hash = (53 * hash) + getX();
    hash = (37 * hash) + Y_FIELD_NUMBER;
    hash = (53 * hash) + getY();
    hash = (37 * hash) + Z_FIELD_NUMBER;
    hash = (53 * hash) + getZ();
    hash = (37 * hash) + PALETTE_ID_FIELD_NUMBER;
    hash = (53 * hash) + getPaletteId();
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static dev.minecraftvideo.contracts.v1.Voxel parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static dev.minecraftvideo.contracts.v1.Voxel parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static dev.minecraftvideo.contracts.v1.Voxel parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(dev.minecraftvideo.contracts.v1.Voxel prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code minecraft_video.contracts.v1.Voxel}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:minecraft_video.contracts.v1.Voxel)
      dev.minecraftvideo.contracts.v1.VoxelOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Voxel_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Voxel_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dev.minecraftvideo.contracts.v1.Voxel.class, dev.minecraftvideo.contracts.v1.Voxel.Builder.class);
    }

    // Construct using dev.minecraftvideo.contracts.v1.Voxel.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      x_ = 0;
      y_ = 0;
      z_ = 0;
      paletteId_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return dev.minecraftvideo.contracts.v1.VoxelWorldProto.internal_static_minecraft_video_contracts_v1_Voxel_descriptor;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.Voxel getDefaultInstanceForType() {
      return dev.minecraftvideo.contracts.v1.Voxel.getDefaultInstance();
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.Voxel build() {
      dev.minecraftvideo.contracts.v1.Voxel result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public dev.minecraftvideo.contracts.v1.Voxel buildPartial() {
      dev.minecraftvideo.contracts.v1.Voxel result = new dev.minecraftvideo.contracts.v1.Voxel(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(dev.minecraftvideo.contracts.v1.Voxel result) {
      int from_bitField0_ = bitField0_;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.x_ = x_;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.y_ = y_;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.z_ = z_;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.paletteId_ = paletteId_;
      }
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof dev.minecraftvideo.contracts.v1.Voxel) {
        return mergeFrom((dev.minecraftvideo.contracts.v1.Voxel)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(dev.minecraftvideo.contracts.v1.Voxel other) {
      if (other == dev.minecraftvideo.contracts.v1.Voxel.getDefaultInstance()) return this;
      if (other.getX() != 0) {
        setX(other.getX());
      }
      if (other.getY() != 0) {
        setY(other.getY());
      }
      if (other.getZ() != 0) {
        setZ(other.getZ());
      }
      if (other.getPaletteId() != 0) {
        setPaletteId(other.getPaletteId());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              x_ = input.readSInt32();
              bitField0_ |= 0x00000001;
              break;
            } // case 8
            case 16: {
              y_ = input.readSInt32();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            case 24: {
              z_ = input.readSInt32();
              bitField0_ |= 0x00000004;
              break;
            } // case 24
            case 32: {
              paletteId_ = input.readUInt32();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private int x_ ;
    /**
     * <code>sint32 x = 1;</code>
     * @return The x.
     */
    @java.lang.Override
    public int getX() {
      return x_;
    }
    /**
     * <code>sint32 x = 1;</code>
     * @param value The x to set.
     * @return This builder for chaining.
     */
    public Builder setX(int value) {

      x_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 x = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearX() {
      bitField0_ = (bitField0_ & ~0x00000001);
      x_ = 0;
      onChanged();
      return this;
    }

    private int y_ ;
    /**
     * <code>sint32 y = 2;</code>
     * @return The y.
     */
    @java.lang.Override
    public int getY() {
      return y_;
    }
    /**
     * <code>sint32 y = 2;</code>
     * @param value The y to set.
     * @return This builder for chaining.
     */
    public Builder setY(int value) {

      y_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 y = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearY() {
      bitField0_ = (bitField0_ & ~0x00000002);
      y_ = 0;
      onChanged();
      return this;
    }

    private int z_ ;
    /**
     * <code>sint32 z = 3;</code>
     * @return The z.
     */
    @java.lang.Override
    public int getZ() {
      return z_;
    }
    /**
     * <code>sint32 z = 3;</code>
     * @param value The z to set.
     * @return This builder for chaining.
     */
    public Builder setZ(int value) {

      z_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>sint32 z = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearZ() {
      bitField0_ = (bitField0_ & ~0x00000004);
      z_ = 0;
      onChanged();
      return this;
    }

    private int paletteId_ ;
    /**
     * <code>uint32 palette_id = 4;</code>
     * @return The paletteId.
     */
    @java.lang.Override
    public int getPaletteId() {
      return paletteId_;
    }
    /**
     * <code>uint32 palette_id = 4;</code>
     * @param value The paletteId to set.
     * @return This builder for chaining.
     */
    public Builder setPaletteId(int value) {

      paletteId_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>uint32 palette_id = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearPaletteId() {
      bitField0_ = (bitField0_ & ~0x00000008);
      paletteId_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:minecraft_video.contracts.v1.Voxel)
  }

  // @@protoc_insertion_point(class_scope:minecraft_video.contracts.v1.Voxel)
  private static final dev.minecraftvideo.contracts.v1.Voxel DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new dev.minecraftvideo.contracts.v1.Voxel();
  }

  public static dev.minecraftvideo.contracts.v1.Voxel getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Voxel>
      PARSER = new com.google.protobuf.AbstractParser<Voxel>() {
    @java.lang.Override
    public Voxel parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Voxel> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Voxel> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public dev.minecraftvideo.contracts.v1.Voxel getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

