// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: voxel_world.proto
// Protobuf Java Version: 4.35.1

package dev.minecraftvideo.contracts.v1;

@com.google.protobuf.Generated
public interface VoxelWorldOrBuilder extends
    // @@protoc_insertion_point(interface_extends:minecraft_video.contracts.v1.VoxelWorld)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 schema_version = 1;</code>
   * @return The schemaVersion.
   */
  int getSchemaVersion();

  /**
   * <code>string minecraft_version = 2;</code>
   * @return The minecraftVersion.
   */
  java.lang.String getMinecraftVersion();
  /**
   * <code>string minecraft_version = 2;</code>
   * @return The bytes for minecraftVersion.
   */
  com.google.protobuf.ByteString
      getMinecraftVersionBytes();

  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  java.util.List<dev.minecraftvideo.contracts.v1.PaletteEntry> 
      getPaletteList();
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  dev.minecraftvideo.contracts.v1.PaletteEntry getPalette(int index);
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  int getPaletteCount();
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  java.util.List<? extends dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder> 
      getPaletteOrBuilderList();
  /**
   * <code>repeated .minecraft_video.contracts.v1.PaletteEntry palette = 3;</code>
   */
  dev.minecraftvideo.contracts.v1.PaletteEntryOrBuilder getPaletteOrBuilder(
      int index);

  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  java.util.List<dev.minecraftvideo.contracts.v1.Voxel> 
      getVoxelsList();
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  dev.minecraftvideo.contracts.v1.Voxel getVoxels(int index);
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  int getVoxelsCount();
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  java.util.List<? extends dev.minecraftvideo.contracts.v1.VoxelOrBuilder> 
      getVoxelsOrBuilderList();
  /**
   * <code>repeated .minecraft_video.contracts.v1.Voxel voxels = 4;</code>
   */
  dev.minecraftvideo.contracts.v1.VoxelOrBuilder getVoxelsOrBuilder(
      int index);

  /**
   * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
   * @return Whether the bounds field is set.
   */
  boolean hasBounds();
  /**
   * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
   * @return The bounds.
   */
  dev.minecraftvideo.contracts.v1.Bounds getBounds();
  /**
   * <code>.minecraft_video.contracts.v1.Bounds bounds = 5;</code>
   */
  dev.minecraftvideo.contracts.v1.BoundsOrBuilder getBoundsOrBuilder();
}
